POST http://localhost:3003/user/signup
Content-Type: application/json

{
    "name": "Lucas",
    "email": "lucas@gmailSDASDASDASDASDSADASDASD.com",
    "password": "abc1254"
}

###
POST http://localhost:3003/user/login
Content-Type: application/json

{
    "email": "lucas@gmailSDASDASDASDASDSADASDASD.com",
    "password": "abc1254"
}

###
GET http://localhost:3003/user
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImQ2YmRhOGUwLTAxZmEtNDUyZS1hYjg2LTFmYjA4OTU2OWFlNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NjM2MDkwMzYsImV4cCI6MTY2MzY1MjIzNn0.TZpUcqk1JvZf90oGEJi8vgvmSavpU532ybfPEVqCDbw

###
DELETE http://localhost:3003/user/d6bda8e0-01fa-452e-ab86-1fb089569ae6
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImI3NzJmZGY0LWM5ZmItNDJjMi1hNGJmLTVhZThiODViNTE5YiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY2MzYxMDg0MCwiZXhwIjoxNjYzNjU0MDQwfQ.UnW6aalc52xq54ToXwT1uV-S1QIxAhaF84dfDda5xIs